# Generated by CoffeeScript 1.6.2
deleteEvent = undefined
saveEvent = undefined
selectedAllDay = undefined
selectedEnd = undefined
selectedEvent = undefined
selectedStart = undefined
selectedEvent = null
selectedStart = null
selectedEnd = null
selectedAllDay = null
saveEvent = ->
  detail = undefined
  location = undefined
  phone = undefined
  title = undefined
  title = $("#title").val()
  location = $("#location").val()
  phone = $("#phone").val()
  detail = $("#detail").val()
  if selectedEvent is null
    selectedEvent = {}
    selectedEvent.title = title
    selectedEvent.start = selectedStart
    selectedEvent.end = selectedEnd
    selectedEvent.allDay = selectedAllDay
    selectedEvent.location = location
    selectedEvent.phone = phone
    selectedEvent.detail = detail
    $("#calendar").fullCalendar "addEventSource", [selectedEvent]
    
    #sync db
    # update event id
    console.log "event added locally"
    
    #
    data = $("#submit_event").serialize() + "&status=new"
    
    #      send event to server
    #       God this code sucks. Need to convert it all to coffeescript and scrub it clean. 2014-08-20
    $.ajax
      data: data # get the form data
      start: selectedStart
      end: selectedEnd
      allDay: selectedAllDay
      type: $("#submit_event").attr("method") # GET or POST
      url: "/forms/visitor/1/event" # the file to call
      success: (response) ->
        console.log "post was a success"

    console.log "event posted to server"
  else
    selectedEvent.title = title
    selectedEvent.location = location
    selectedEvent.phone = phone
    selectedEvent.detail = detail
    $("#calendar").fullCalendar "updateEvent", selectedEvent
    
    #sync db
    console.log "event updated"
  $(".closeBtn").click()
  false


#    return this.preventDefault()
#    return false;
deleteEvent = ->
  $("#calendar").fullCalendar "removeEvents", selectedEvent._id
  
  #sync db
  data = $("#submit_event").serialize() + "&status=delete" + "&id=" + selectedEvent._id
  $.ajax
    data: data # get the form data
    type: $("#submit_event").attr("method") # GET or POST
    url: "/forms/visitor/1/event" # the file to call
    success: (response) ->
      console.log "post was a success"

  $(".closeBtn").click()
  false

$(document).ready ->
  $("#external-events div.external-event").each ->
    eventObject = undefined
    eventObject = title: $.trim($(this).text())
    $(this).data "eventObject", eventObject
    $(this).draggable
      zIndex: 999
      revert: true
      revertDuration: 0


  $("#calendar").fullCalendar
    header:
      left: "prev,next today"
      center: "title"
      right: "month,agendaWeek,agendaDay"

    selectable: true
    editable: true
    select: (start, end, allDay) ->
      $(".modalLink").click()
      selectedEvent = null
      selectedStart = start
      selectedEnd = end
      selectedAllDay = allDay

    eventClick: (calEvent, jsEvent, view) ->
      selectedEvent = calEvent
      $("#title").val calEvent.title
      $("#location").val calEvent.location
      $("#phone").val calEvent.phone
      $("#detail").val calEvent.detail
      $(".modalLink").click()



# return $("#calendar").fullCalendar('addEventSource', "{{event_data}}");
$(".modalLink").modal
  trigger: ".modalLink"
  olay: "div.overlay"
  modals: "div.modal"
  animationEffect: "slidedown"
  animationSpeed: 400
  moveModalSpeed: "slow"
  background: "00c2ff"
  opacity: 0.8
  openOnLoad: false
  docClose: true
  closeByEscape: true
  moveOnScroll: true
  resizeWindow: true
  video: "http://player.vimeo.com/video/9641036?color=eb5a3d"
  close: ".closeBtn"
